<?php

namespace AppBundle\Repository;

use AppBundle\Entity\Etudiant;
use AppBundle\Entity\Evaluation;
use Doctrine\ORM\EntityRepository;

/**
 * NoteRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class EvaluationRepository extends EntityRepository
{

    public function getEvaluation($id)
    {
        $sql = 'select ev, cl, mat, per, an from AppBundle:Evaluation ev '
            . 'join ev.classe cl '
            . 'join ev.matiere mat '
            . 'join ev.periode per '
            . 'join ev.anScolaire an '
            . 'where ev.id = :id';
        return $query = $this->_em->createQuery($sql)
            ->setParameter('id', $id)
            ->getOneOrNullResult();
    }

    public function getEvaluationsByEtudiant(Etudiant $etudiant)
    {
        return $this->createQueryBuilder('e')
            ->addSelect('a')
            ->join('e.notes', 'n')
            ->join('e.anScolaire', 'a')
            ->where('n.etudiant = :etudiant')
            ->groupBy('a')
            ->orderBy('a.nom', 'DESC')
            ->setParameter('etudiant', $etudiant);

        // $query = 'SELECT an.id AS aid,
        //     an.nom AS annee,
        //     sem.id AS sid, sem.nom AS semestre,
        //     cl.id AS cid, cl.nom AS classe
        //     FROM sf3_evaluation ev
        //         JOIN sf3_an_scolaire an ON an.id = ev.an_scolaire_id
        //         JOIN sf3_ue ue ON ue.id = ev.ue_id
        //         JOIN sf3_classe cl ON cl.id = ue.classe_id
        //         JOIN sf3_semestre sem ON sem.id = ue.semestre_id
        //         JOIN sf3_note nt ON ev.id = nt.evaluation_id
        //         WHERE nt.etudiant_id = :eid
        //     GROUP BY an.id, cl.id, sem.id
        //     ORDER BY an.nom DESC, cl.nom DESC, sem.nom DESC';

        // $db = $this->_em->getConnection();
        // $stmt = $db->executeQuery($query, ['eid' => $etudiant->getId()]);
        // return $stmt->fetchAll();
    }

}
