<?php

namespace AppBundle\Repository;

/**
 * ListeUeRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ListeUeRepository extends \Doctrine\ORM\EntityRepository
{
}
